name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  snyk_monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Bootstrap poetry
        run: |
          curl -sL https://install.python-poetry.org | python - -y
      - name: Snyk test
        run: snyk test --org=ie-playground --file=poetry.lock --package-manager=poetry --severity-threshold=critical --project-lifecycle=development
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk monitor
        run: snyk monitor --org=ie-playground --file=poetry.lock --package-manager=poetry --project-lifecycle=development
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  docker_build:
    runs-on: ubuntu-latest
    needs: snyk_monitor
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image for scanning
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          platforms: ${{matrix.platform}}
          tags: ghcr.io/snyk-playground/snyk-sync:${{ github.sha }}
      - name: Snyk Container Test
        run: snyk container test ghcr.io/snyk-playground/snyk-sync:${{ github.sha }} --platform=${{matrix.platform}} --exclude-base-image-vulns --file=Dockerfile --org=ie-playground --severity-threshold=critical --project-lifecycle=development
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk Container Monitor
        run: snyk container monitor ghcr.io/snyk-playground/snyk-sync:$GITHUB_SHA --platform=${{matrix.platform}} --file=Dockerfile --project-name=snyk-sync-container-${{matrix.platform}} --org=ie-playground --project-lifecycle=development --project-tags=gitsha=$GITHUB_SHA
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{matrix.platform}}
          push: true
          tags: |
            snyk-playground/snyk-sync:${{ github.sha }}
            ghcr.io/snyk-playground/snyk-sync:${{ github.sha }}
